export const BASE = "https://api.x.com/2";
export const RATE_DELAY_MS = 350;
export const FIELDS =
  "tweet.fields=created_at,public_metrics,author_id,conversation_id,entities&expansions=author_id&user.fields=username,name,profile_image_url,verified,public_metrics";

export const STOPWORDS = new Set([
  "the",
  "and",
  "for",
  "new",
  "now",
  "first",
  "not",
  "out",
  "one",
  "more",
  "their",
  "there",
  "about",
  "into",
  "from",
  "with",
  "this",
  "that",
  "then",
  "than",
  "while",
  "where",
  "which",
  "what",
  "when",
  "will",
  "your",
  "just",
  "have",
  "been",
  "were",
  "they",
  "them",
  "does",
  "did",
  "are",
  "you",
  "our",
  "can",
  "under",
  "specific",
  "shows",
  "show",
  "today",
  "release",
  "releasing",
  "released",
  "using",
  "result",
  "results",
  "that",
  "https",
  "http",
  "were",
]);

export const ANALYZE_OUTPUT_VERSION = "2";
export const DISCOVER_OUTPUT_VERSION = "2";
